name: samarretes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  camera: ^0.11.1
  video_player: ^2.8.2
  just_audio: ^0.9.36
  flutter_sound: ^9.1.6
  video_player_android: ^2.7.16
  image_picker: ^1.0.4
  audioplayers: ^6.2.0
  file_picker: ^9.0.2
  flutter_gherkin: ^2.0.0
  test: ^1.25.15
  build_runner: ^2.4.15
  glob: ^2.1.3
  gherkin: ^2.0.8

dev_dependencies:
  flutter_gherkin: ^2.0.0
  gherkin: ^2.0.0
  glob: ^2.1.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.25.15





flutter:
  uses-material-design: true
  assets: 
    - assets/main313.png
    - assets/tapestry.png
    - assets/dice_1.svg
    - assets/dice_2.svg
    - assets/dice_3.svg
    - assets/dice_4.svg
    - assets/dice_5.svg
    - assets/dice_6.svg
    - assets/videoPrueba.mp4
    - assets/audioPrueba1.mp3
    - assets/audioPrueba2.mp3
    - assets/audioPrueba3.mp3
