name: samarretes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  camera: ^0.10.5+9
  video_player: ^2.8.2
  just_audio: ^0.9.36
  flutter_sound: ^9.1.6
  video_player_android: ^2.7.16
  image_picker: ^1.0.4
  audioplayers: ^6.2.0
  file_picker: ^8.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.16.0
  flutter_lints: ^5.0.0
  youtube_player_flutter: ^8.1.2


flutter:
  uses-material-design: true
  assets: 
    - assets/main313.png
    - assets/tapestry.png
    - assets/dice_1.svg
    - assets/dice_2.svg
    - assets/dice_3.svg
    - assets/dice_4.svg
    - assets/dice_5.svg
    - assets/dice_6.svg
    - assets/videoPrueba.mp4
    - assets/audioPrueba1.mp3
    - assets/audioPrueba2.mp3
    - assets/audioPrueba3.mp3
